services:
#  jekyll:
#    image: jekyll/jekyll:latest
#    command: jekyll serve --force_polling
#    ports:
#      - 4000:4000
#    volumes:
#      - .:/srv/jekyll


  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - '4000:4000'